from __future__ import annotations

class SentencePieceProcessor:
    def __init__(self) -> None: ...
    def Load(self, model_file: str) -> bool: ...
    def EncodeAsPieces(self, text: str) -> list[str]: ...
    def EncodeAsIds(self, text: str) -> list[int]: ...
    def DecodePieces(self, pieces: list[str]) -> str: ...
    def DecodeIds(self, ids: list[int]) -> str: ...
