from __future__ import annotations

from collections.abc import Sequence
from typing import Final

class SentencePieceProcessor:
    def __init__(self) -> None: ...
    def Load(self, model_file: str) -> bool: ...
    def encode(self, text: str, out_type: type[str]) -> list[str]: ...
    def decode(self, pieces: Sequence[str]) -> str: ...

__all__: Final[list[str]]
